config/routes.rb
AudioRecordRails::Application.routes.draw do
  devise_for :users

  resources :readings, only: [:show, :destroy]
  resources :poems, only: :index
  resources :poems, except: [:destroy, :update, :index] do
    resources :readings, only: [:index, :create]
  end

  get    '/tags/:tag', to: 'poems#index', as: 'tag'
  get    '/tag_cloud', to: 'tags#index', as: 'tag_cloud'
  get    '/user', to: 'users#user_page', as: 'user'

  post   'favorites/:type/:id', to: 'favorites#create', as: 'new_favorite'
  delete 'favorites/:type/:id', to: 'favorites#destroy', as: 'destroy_favorite'

  root 'static_pages#home'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favoriteable, polymorphic: true, touch: true

  # Allows calling user.favorites.poems, user.readings.poems
  scope :poems, -> { where(favoriteable_type: 'Poem')}
  scope :readings, -> { where(favoriteable_type: 'Reading')}

  validates :user_id, presence: true
  validates :user_id, uniqueness: { scope:
      [:favoriteable_id, :favoriteable_type]
    }
end

app/models/poem.rb
class Poem < ActiveRecord::Base
  fuzzily_searchable :title, :author, :body
  acts_as_taggable

  has_many :readings, dependent: :destroy
  has_many :favorites, as: :favoriteable, dependent: :destroy
  before_create :added_at

  validates :title,
    uniqueness: { scope: :author, message: "already exists"},
    presence: true
  validates :author, presence: true
  validates :body, presence: true

  def added_at
    self.added_at = Time.now()
  end

  def self.find_fuzzy(params)
    first_search = true
    poems = []
    params.each do |term, input|
      results = Poem.send("find_by_fuzzy_#{term}", input, {limit: 25})
      poems = (first_search && results) || poems & results
      first_search = false
    end
    return (poems || [])
  end
end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :poem
  belongs_to :user
  has_many :favorites, as: :favoriteable, dependent: :destroy

  delegate :username, to: :user
  delegate :url, to: :wav, prefix: true # reading.wav_url

  has_attached_file :wav
  validates_attachment :wav,
    content_type: { content_type: "audio/wav" },
    size: { in: 0..100.megabytes }
end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
  include Fuzzily::Model
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites
  has_many :readings, inverse_of: :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :load_favoriteable

  def create
    @favorite = @favoriteable.favorites.new(user: current_user)
    @favorite.save!
    render json: @favorite
  end

  def destroy
    @favorite = @favoriteable.favorites.where(user: current_user).first
    @favorite.destroy!
    render json: @favorite
  end

  private
  def load_favoriteable
    resource, id = request.path.split('/')[-2,2]
    @favoriteable = resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def new
    @poem = Poem.new
  end

  def create
    @poem = Poem.new(poem_params)
    if @poem.save
      redirect_to @poem, notice: 'Poem successfully created'
    else
      flash.now[:alert] = @poem.errors.full_messages.join(', ')
      render action: 'new'
    end
  end

  def show
    @poem = Rails.cache.fetch("poem_#{params[:id]}", expires_in: 2.day) do
      Poem.includes(:favorites).includes(:tags).find(params[:id])
    end
    if current_user.present?
      @user_fav = @poem.favorites.where(user: current_user).present?
    end
  end

  def index
    if params[:tag]
      @poems = Poem.includes(:tags).tagged_with(params[:tag]).order(:title)
      @search = { tag: params[:tag] }
    elsif params[:fuzzies].present?
      search_params = params[:fuzzies].reject {|k,v| v.empty? }
      @poems = Poem.includes(:tags).find_fuzzy(search_params)
      @search = search_params
    else
      @poems = Poem.includes(:tags).order(added_at: :desc).limit(5)
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def poem_params
    params.require(:poem).permit(:title, :author, :body, :tag_list)
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  def create
    reading = Reading.new(wav: params[:wav], description: params[:description],
                          user: current_user, poem_id: params[:poem_id])
    reading.save!
    render reading
    # Reading.delay.save
    # thread.new
  end

  def index
    @readings = Reading.includes(:user).where(poem_id: params[:poem_id])
    # Construct an array of the user's favorite readings
    if current_user.present?
      @user_favs = current_user.favorites.readings.pluck(:favoriteable_id)
    end
  end

  def show
    reading = Reading.find(params[:id])
    render reading
  end

  def destroy
    @reading = Reading.find(params[:id])
    if current_user == @reading.user && @reading.destroy
      render @reading
    else
      render json: { error: @reading.errors }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Poem.tag_counts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def user_page
    respond_to do |format|
      @user = current_user
      format.html
      format.json do
        @user_readings = Reading.where(user: @user)
        favorites = @user.favorites.includes(:favoriteable).map(&:favoriteable)
        @poems = favorites.select {|favorite| favorite.class == Poem }
        all_readings = favorites - @poems
        # set user_favs as the ids of favorite readings so the partial can
        # attach the required user_fav: true attribute
        @user_favs = all_readings.map(&:id)
        @user_readings = Reading.where(user: @user)
        # remove any overlap if user has favorited her own readings
        @readings = all_readings - @user_readings
        # on users page we want recordings to link to their poem
        @link_poem = true
      end
    end
  end
end

app/views/audio/index.html.haml
%h1 Is this thing on?
%button.btn.btn-success#toggle-recording Start Recording
%button.btn.btn-warning.hidden#save-recording Save to Server
%input#recording-desc.hidden{ type: "text", placeholder: "Description" }/

app/views/layouts/_navbar.html.haml
%nav.main-nav
  %ul#nav-list.nav-list
    - if user_signed_in?
      %li.nav-li= link_to 'logout', destroy_user_session_path, method: :delete, class: 'nav-link letterpress'
      %li.nav-li= link_to 'my playetry', user_path, class: 'nav-link letterpress'
    - else
      %li.nav-li= link_to 'login', new_user_session_path, class: 'nav-link letterpress'
      %li.nav-li= link_to 'signup', new_user_registration_path, class: 'nav-link letterpress'
    %li.nav-li= link_to 'find poems', poems_path, class: 'nav-link letterpress'
    %li.nav-li= link_to 'write', new_poem_path, class: 'nav-link letterpress'
    %li.nav-li
      %h1.nav-logo= link_to 'playetry', root_path

app/views/layouts/_user_widget.html.haml
- if user_signed_in?
  %p Welcome #{ link_to current_user.username, root_path }
  = link_to 'Logout', destroy_user_session_path, method: :delete
- else
  %p You are not signed in.
  = link_to 'Login', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Playetry
    %meta{property: "og:image", content: image_url('playetry-og.png')}
    %meta{property: "og:site_name", content: "playetry"}
    %meta{property: "og:description", content: "Read, write, listen to and record poetry"}
    %meta{property: "og:url", content: "http://playetry.herokuapp.com"}
    %meta{property: "og:title", content: "playetry"}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body{'data-controller' => "#{ controller.controller_path }", 'data-action' => "#{ controller.action_name }", 'data-current-user' => "#{ current_user.try(:id) }" }
    = render 'layouts/navbar'
    %p.notice= notice
    %p.alert= alert
    .container
      = yield

app/views/poems/_form.html.haml
= form_for @poem do |f|
  .poem-title.poem-topbot
    = f.text_field :title, class: 'poem-input title letterpress', id: 'new-title', placeholder: 'Click to enter title', autocomplete: false
    = f.text_field :author, class: 'poem-input author letterpress', id: 'new-author', placeholder: 'Click to enter author', autocomplete: false
  .poem-body
    = f.text_area :body, id: 'new-body'
  .poem-tags.poem-topbot
    = text_field_tag "new-tags", "", class: 'poem-input author letterpress', placeholder: 'Enter tags (with a comma after each)', data: { autocomplete_source: Poem.tag_counts_on(:tags).order(:name).map(&:name) }, autocomplete: false
    = f.hidden_field :tag_list, id: 'finished-tags', class: 'hidden'
    = f.button "Submit", type: 'submit', class: 'btn btn-warning btn-submit', id: 'submit-poem'
    %ul#tag-list

app/views/poems/_poem.html.haml
%li
  .poem-index{"data-poem-id" => "#{poem.id}"}
    %h3.poem-index-title
      = link_to "#{poem.title}", poem, class: "poem-link letterpress"
    %h6.poem-index-author.letterpress
      by
      %span.author{"data-author-name" => "#{poem.author}"}= poem.author

app/views/poems/index.html.haml
.search-bar
  %input.poem-input.author.letterpress#title-search{type: 'text', placeholder: 'Title Search'}
  %input.poem-input.author.letterpress#author-search{type: 'text', placeholder: 'Author Search'}
  %input.poem-input.author.letterpress#body-search{type: 'text',   placeholder: 'Body Search'}
  %button.poem-index-title.letterpress.clear-button#send-search Search
.poems-index.col-xs-12.col-sm-7
  %h1 browse poems
  %h3#search-by
    - if @search
      = "#{pluralize(@poems.count, 'result')} for"
      %span.search-param= "[tag] #{@search[:tag]}"
    - else
      recent additions
  %ul#poems-list.poems-list
    = render @poems
.tags-index.col-xs-12.col-sm-5
  %h1 get inspired!
  %h3 see poems by tag
  #tags-list

app/views/poems/new.html.haml
.col-xs-12
  %h1.verb write
  .poem-container.full-width
    = render 'form'

app/views/poems/show.html.haml
.poem-container.left.col-xs-12.col-md-7{ "data-poem-id" => "#{@poem.id}" }
  %h1#read.verb read
  .poem-title.poem-topbot
    .fav-poem
      - if @user_fav
        %span.glyphicon.glyphicon-heart-empty.is-fav
      - elsif current_user
        %span.glyphicon.glyphicon-heart-empty
      - else
        %span.glyphicon
    %h1.poem-input.title.letterpress #{@poem.title}
    %h3.poem-input.author.letterpress by #{@poem.author}
  .poem-body.show
    %pre #{@poem.body}
  .poem-topbot#new-reading-container
    .poem-show-tags
      %ul#poem-tag-list
        = render partial: 'tags/tag', collection: @poem.tags, as: :tag
    %button.btn.btn-success#toggle-recording REC
    #new-reading-inner
      %h3.poem-input.title.letterpress
        - if current_user.present?
          Read this poem!
        - else
          #{link_to "Sign in", new_user_session_path} to record.
      %input#recording-desc.poem-input.author.letterpress.hidden{ type: "text", placeholder: "Click to enter a description"}/
      %button.btn.btn-warning.hidden#save-recording Save!
.right.col-xs-12.col-md-4
  %h1#listen.verb listen
  .readings-container.width-fix
    %ul#reading-list.reading-column-ul

-# Immediately request JSON for the relevant readings and render them with hbs
%script
  Playetry.audioControl.getReadings("#{@poem.id}")

app/views/static_pages/home.html.haml
.main-splash
  %h1.home-title playetry
  %h1.poem-input.title.letterpress write.read.speak.feel
  .col-xs-12#big-tag-cloud
    %p.main-p find poems, record yourself reading them, write your own, explore existing topics

app/views/tags/_tag.html.haml
%li
  .mini-tag
    = link_to tag_path(tag.name), class: "tag-link" do
      %p #{tag.name}

app/views/users/user_page.html.haml
.user-container
  %h1 #{@user.username}
  .poems-index
    %h3#fav-poems-header your favorite poems
    %ul#fav-poems.poems-list
  .col-xs-12.col-md-6
    %h3#fav-readings-header your favorite readings
    .readings-container.spacer
      %ul#fav-readings.reading-column-ul
  .col-xs-12.col-md-6
    %h3#user-readings-header readings you've done
    .readings-container
      %ul#user-readings.reading-column-ul